In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv("/content/Wholesale customers data.csv")
df

Channel  Region  Fresh   Milk  Grocery   Frozen  Detergents_Paper  \
0          2       3  12669   9656   7561.0    214.0            2674.0   
1          2       3   7057   9810   9568.0   1762.0            3293.0   
2          2       3   6353   8808   7684.0   2405.0            3516.0   
3          1       3  13265   1196   4221.0   6404.0             507.0   
4          2       3  22615   5410   7198.0   3915.0            1777.0   
..       ...     ...    ...    ...      ...      ...               ...   
411        1       3      3  12051  16027.0  13135.0             182.0   
412        1       3  39228   1431    764.0   4510.0              93.0   
413        2       3  14531  15488  30243.0    437.0           14841.0   
414        1       3  10290   1981   2232.0   1038.0             168.0   
415        1       3   2787   1698   2510.0     65.0             477.0   

     Delicassen  
0        1338.0  
1        1776.0  
2        7844.0  
3        1788.0  
4        5185.0  
..          ...  
411      2204.0  
412      2346.0  
413      1867.0  
414      2125.0  
415        52.0  

[416 rows x 8 columns]

In [ ]:
df.columns

Index(['Channel', 'Region', 'Fresh', 'Milk', 'Grocery', 'Frozen',
       'Detergents_Paper', 'Delicassen'],
      dtype='object')

In [ ]:
df.head()

Channel  Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen
0        2       3  12669  9656   7561.0   214.0            2674.0      1338.0
1        2       3   7057  9810   9568.0  1762.0            3293.0      1776.0
2        2       3   6353  8808   7684.0  2405.0            3516.0      7844.0
3        1       3  13265  1196   4221.0  6404.0             507.0      1788.0
4        2       3  22615  5410   7198.0  3915.0            1777.0      5185.0

In [ ]:
df.tail()

Channel  Region  Fresh   Milk  Grocery   Frozen  Detergents_Paper  \
411        1       3      3  12051  16027.0  13135.0             182.0   
412        1       3  39228   1431    764.0   4510.0              93.0   
413        2       3  14531  15488  30243.0    437.0           14841.0   
414        1       3  10290   1981   2232.0   1038.0             168.0   
415        1       3   2787   1698   2510.0     65.0             477.0   

     Delicassen  
411      2204.0  
412      2346.0  
413      1867.0  
414      2125.0  
415        52.0

In [ ]:
df.isna().sum()

Channel             0
Region              0
Fresh               0
Milk                0
Grocery             1
Frozen              1
Detergents_Paper    3
Delicassen          2
dtype: int64

In [ ]:
#removing null vslues using mode operator
a=df['Grocery'].mode()
df['Grocery'].fillna(a,inplace=True)
a
b=df['Frozen'].mode()
df['Frozen'].fillna(a,inplace=True)
b
c=df['Detergents_Paper'].mode()
df['Detergents_Paper'].fillna(a,inplace=True)
c
d=df['Delicassen'].mode()
df['Delicassen'].fillna(a,inplace=True)
d

0    3.0
dtype: float64

In [ ]:
df1=df.groupby('Channel') ['Channel'].count()
df1

Channel
1    282
2    134
Name: Channel, dtype: int64

In [ ]:
x=df.iloc[:,:-1].values
x

array([[2.0000e+00, 3.0000e+00, 1.2669e+04, ..., 7.5610e+03, 2.1400e+02,
        2.6740e+03],
       [2.0000e+00, 3.0000e+00, 7.0570e+03, ..., 9.5680e+03, 1.7620e+03,
        3.2930e+03],
       [2.0000e+00, 3.0000e+00, 6.3530e+03, ..., 7.6840e+03, 2.4050e+03,
        3.5160e+03],
       ...,
       [2.0000e+00, 3.0000e+00, 1.4531e+04, ..., 3.0243e+04, 4.3700e+02,
        1.4841e+04],
       [1.0000e+00, 3.0000e+00, 1.0290e+04, ..., 2.2320e+03, 1.0380e+03,
        1.6800e+02],
       [1.0000e+00, 3.0000e+00, 2.7870e+03, ..., 2.5100e+03, 6.5000e+01,
        4.7700e+02]])

In [ ]:
y=df.iloc[:,-1].values
y

array([1.3380e+03, 1.7760e+03, 7.8440e+03, 1.7880e+03, 5.1850e+03,
       1.4510e+03, 5.4500e+02, 2.5660e+03, 7.5000e+02, 2.0980e+03,
       1.7440e+03, 4.9700e+02, 2.9310e+03, 6.0200e+02, 2.1680e+03,
       4.1200e+02, 1.0800e+03, 4.4780e+03, 3.1810e+03, 5.0100e+02,
       2.1240e+03, 5.6900e+02,        nan, 8.3300e+02, 5.1800e+02,
       5.2060e+03, 8.2300e+02, 2.9630e+03, 9.8500e+02, 4.0500e+02,
       1.0830e+03, 3.9500e+02, 4.3600e+02, 4.6260e+03, 7.1400e+02,
       4.3300e+02, 2.9160e+03, 5.8640e+03, 2.8020e+03, 4.6000e+01,
       7.2000e+01, 6.5000e+01, 4.9850e+03, 1.4520e+03, 6.4650e+03,
       1.4760e+03, 1.1630e+03, 2.1620e+03, 3.0100e+02, 1.2780e+03,
       2.2400e+02, 1.3330e+03, 1.1300e+03, 1.3400e+03, 1.2820e+03,
       4.3600e+02, 1.6030e+03, 2.2500e+02, 2.0170e+03, 9.6400e+02,
       1.4472e+04, 1.8100e+02, 6.4800e+02, 1.7800e+03, 9.7500e+02,
       8.9400e+02, 1.0090e+03, 1.6700e+02, 1.6530e+03, 5.2900e+02,
       1.5600e+02, 2.3420e+03, 7.7200e+02, 1.2000e+02, 2.9440e

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_test

array([[2.0000e+00, 3.0000e+00, 5.5310e+03, 1.5726e+04, 2.6870e+04,
        2.3670e+03, 1.3726e+04],
       [2.0000e+00, 2.0000e+00, 2.4300e+02, 1.2939e+04, 8.8520e+03,
        7.9900e+02, 3.9090e+03],
       [1.0000e+00, 3.0000e+00, 8.5330e+03, 5.5060e+03, 5.1600e+03,
        1.3486e+04, 1.3770e+03],
       [1.0000e+00, 3.0000e+00, 1.5587e+04, 1.0140e+03, 3.9700e+03,
        9.1000e+02, 1.3900e+02],
       [2.0000e+00, 3.0000e+00, 2.1900e+02, 9.5400e+03, 1.4403e+04,
        2.8300e+02, 7.8180e+03],
       [2.0000e+00, 3.0000e+00, 6.6000e+02, 8.4940e+03, 1.8622e+04,
        1.3300e+02, 6.7400e+03],
       [2.0000e+00, 3.0000e+00, 4.0480e+03, 5.1640e+03, 1.0391e+04,
        1.3000e+02, 8.1300e+02],
       [2.0000e+00, 1.0000e+00, 1.1072e+04, 5.9890e+03, 5.6150e+03,
        8.3210e+03, 9.5500e+02],
       [2.0000e+00, 3.0000e+00, 1.0850e+04, 7.5550e+03, 1.4961e+04,
        1.8800e+02, 6.8990e+03],
       [1.0000e+00, 3.0000e+00, 1.3779e+04, 1.9700e+03, 1.6480e+03,
        5.9600e+02, 2.2

In [ ]:
x_test

array([[2.0000e+00, 3.0000e+00, 5.5310e+03, 1.5726e+04, 2.6870e+04,
        2.3670e+03, 1.3726e+04],
       [2.0000e+00, 2.0000e+00, 2.4300e+02, 1.2939e+04, 8.8520e+03,
        7.9900e+02, 3.9090e+03],
       [1.0000e+00, 3.0000e+00, 8.5330e+03, 5.5060e+03, 5.1600e+03,
        1.3486e+04, 1.3770e+03],
       [1.0000e+00, 3.0000e+00, 1.5587e+04, 1.0140e+03, 3.9700e+03,
        9.1000e+02, 1.3900e+02],
       [2.0000e+00, 3.0000e+00, 2.1900e+02, 9.5400e+03, 1.4403e+04,
        2.8300e+02, 7.8180e+03],
       [2.0000e+00, 3.0000e+00, 6.6000e+02, 8.4940e+03, 1.8622e+04,
        1.3300e+02, 6.7400e+03],
       [2.0000e+00, 3.0000e+00, 4.0480e+03, 5.1640e+03, 1.0391e+04,
        1.3000e+02, 8.1300e+02],
       [2.0000e+00, 1.0000e+00, 1.1072e+04, 5.9890e+03, 5.6150e+03,
        8.3210e+03, 9.5500e+02],
       [2.0000e+00, 3.0000e+00, 1.0850e+04, 7.5550e+03, 1.4961e+04,
        1.8800e+02, 6.8990e+03],
       [1.0000e+00, 3.0000e+00, 1.3779e+04, 1.9700e+03, 1.6480e+03,
        5.9600e+02, 2.2

In [ ]:
from sklearn.preprocessing import minmax_scale
scaler=minmax_scale()
scaler.fit(x_)

TypeError: ignored